export const FAST_ACTION_VERBS = ['READ_FILE','SEARCH_CODE','APPLY_PATCH','RUN_COMMAND','CHECK_GIT','OPEN_FILE','RETRY','DONE','ESCALATE'] as const
export type FastActionVerb=typeof FAST_ACTION_VERBS[number]
export type NormalizedFastActionKind='source.read'|'source.write'|'shell.execute'|'git.status'|'git.commit'|'git.push'|'surface.open'|'runtime.retry'|'workflow.complete'|'runtime.escalation'
interface Base<V extends FastActionVerb,P,R>{verb:V;params:P;writeScope:string[];result?:R}
export type ReadFileAction=Base<'READ_FILE',{path:string;maxBytes?:number},{path:string;data:string;size:number;byteSize:number;truncated:boolean}>
export type SearchCodeAction=Base<'SEARCH_CODE',{query:string;path?:string;regex?:boolean;caseSensitive?:boolean;includeHidden?:boolean;maxResults?:number},{matches:unknown[];truncated:boolean}>
export type ApplyPatchAction=Base<'APPLY_PATCH',{patch:string},{applied:boolean;changedPaths:string[]}>
export type RunCommandAction=Base<'RUN_COMMAND',{command:string;cwd?:string},{exitCode:number;stdout:string;stderr:string;truncated:boolean}>
export type CheckGitAction=Base<'CHECK_GIT',{operation:'status'|'commit'|'push';message?:string;remote?:string},{operation:'status'|'commit'|'push';entries?:unknown[];commit?:string;pushed?:boolean;truncated?:boolean}>
export type OpenFileAction=Base<'OPEN_FILE',{path:string;line?:number},{path:string;line?:number;opened:boolean}>
export type RetryAction=Base<'RETRY',{reason:string},{queued:boolean}>
export type DoneAction=Base<'DONE',{summary:string},{completed:boolean;summary:string}>
export type EscalateAction=Base<'ESCALATE',{reason:string;tier?:string},{escalated:boolean;reason:string;tier?:string}>
export type FastAction=ReadFileAction|SearchCodeAction|ApplyPatchAction|RunCommandAction|CheckGitAction|OpenFileAction|RetryAction|DoneAction|EscalateAction
export interface FastActionPlan{version:1;expectedRevision?:string;actions:FastAction[]}
const OPEN='<nd-dsh-fast-actions>',CLOSE='</nd-dsh-fast-actions>',MAX_ACTIONS=32,MAX_TEXT=256*1024
export function parseFastActionPlan(text:string):FastActionPlan|undefined{const start=text.indexOf(OPEN);if(start<0)return;const end=text.indexOf(CLOSE,start+OPEN.length);if(end<0)throw new Error('Fast-action block is missing its closing tag.');const raw=text.slice(start+OPEN.length,end).trim();if(!raw||raw.length>MAX_TEXT)throw new Error('Fast-action block is empty or too large.');let parsed:unknown;try{parsed=JSON.parse(raw)}catch(e){throw new Error('Fast-action block is not valid JSON: '+err(e))}const o=obj(parsed,'Fast-action plan');if(o.version!==1)throw new Error('Fast-action plan version must be 1.');if(!Array.isArray(o.actions)||o.actions.length<1||o.actions.length>MAX_ACTIONS)throw new Error('Fast-action plan action count is invalid.');const rev=optString(o.expectedRevision,'expectedRevision',256);return{version:1,...(rev?{expectedRevision:rev}:{}),actions:o.actions.map(parseAction)}}
export function normalizedActionKind(a:FastAction):NormalizedFastActionKind{switch(a.verb){case'READ_FILE':case'SEARCH_CODE':return'source.read';case'APPLY_PATCH':return'source.write';case'RUN_COMMAND':return'shell.execute';case'CHECK_GIT':return a.params.operation==='status'?'git.status':a.params.operation==='commit'?'git.commit':'git.push';case'OPEN_FILE':return'surface.open';case'RETRY':return'runtime.retry';case'DONE':return'workflow.complete';case'ESCALATE':return'runtime.escalation'}}
export function isFastActionDeterministicRead(a:FastAction){return a.verb==='READ_FILE'||a.verb==='SEARCH_CODE'||(a.verb==='CHECK_GIT'&&a.params.operation==='status')||a.verb==='OPEN_FILE'||a.verb==='DONE'}
function parseAction(value:unknown,index:number):FastAction{const o=obj(value,'Fast action '+(index+1)),verb=req(o.verb,'verb',64) as FastActionVerb;if(!(FAST_ACTION_VERBS as readonly string[]).includes(verb))throw new Error('Unknown fast-action verb: '+verb);const p=obj(o.params,verb+'.params'),writeScope=list(o.writeScope,verb+'.writeScope');switch(verb){case'READ_FILE':return{verb,params:{path:req(p.path,'path'),...oi(p.maxBytes,'maxBytes',1,1048576)},writeScope};case'SEARCH_CODE':return{verb,params:{query:req(p.query,'query'),...os(p.path,'path'),...ob(p.regex,'regex'),...ob(p.caseSensitive,'caseSensitive'),...ob(p.includeHidden,'includeHidden'),...oi(p.maxResults,'maxResults',1,200)},writeScope};case'APPLY_PATCH':need(writeScope,verb);return{verb,params:{patch:req(p.patch,'patch',MAX_TEXT)},writeScope};case'RUN_COMMAND':need(writeScope,verb);return{verb,params:{command:req(p.command,'command',32000),...os(p.cwd,'cwd')},writeScope};case'CHECK_GIT':{const operation=req(p.operation,'operation',16);if(!['status','commit','push'].includes(operation))throw new Error('Invalid CHECK_GIT operation.');if(operation!=='status')need(writeScope,verb);return{verb,params:{operation:operation as CheckGitAction['params']['operation'],...os(p.message,'message'),...os(p.remote,'remote',256)},writeScope}}case'OPEN_FILE':return{verb,params:{path:req(p.path,'path'),...oi(p.line,'line',1,10000000)},writeScope};case'RETRY':return{verb,params:{reason:req(p.reason,'reason')},writeScope};case'DONE':return{verb,params:{summary:req(p.summary,'summary',16000)},writeScope};case'ESCALATE':return{verb,params:{reason:req(p.reason,'reason'),...os(p.tier,'tier',128)},writeScope}}}
function need(v:string[],x:string){if(!v.length)throw new Error(x+' must declare a non-empty writeScope.')}function obj(v:unknown,l:string):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(l+' must be an object.');return v as Record<string,unknown>}function req(v:unknown,l:string,m=4096){if(typeof v!=='string')throw new Error(l+' must be a string.');const s=v.trim();if(!s||s.length>m||s.includes('\0'))throw new Error(l+' is invalid.');return s}function optString(v:unknown,l:string,m:number){return v===undefined||v===null||v===''?undefined:req(v,l,m)}function os(v:unknown,l:string,m=4096){const x=optString(v,l,m);return x===undefined?{}:{[l]:x}}function ob(v:unknown,l:string){if(v===undefined||v===null)return{};if(typeof v!=='boolean')throw new Error(l+' must be boolean.');return{[l]:v}}function oi(v:unknown,l:string,min:number,max:number){if(v===undefined||v===null)return{};if(!Number.isInteger(v)||(v as number)<min||(v as number)>max)throw new Error(l+' is out of range.');return{[l]:v as number}}function list(v:unknown,l:string){if(!Array.isArray(v)||v.length>32)throw new Error(l+' must be an array.');return v.map((x,i)=>req(x,l+'['+i+']'))}function err(e:unknown){return e instanceof Error?e.message:String(e)}
