import type { SymbolId, SymbolInfo, BetMap } from '../types/index.js'

export const SYMBOL_IDS: readonly SymbolId[] = [
  'tiger',
  'gourd',
  'shrimp',
  'fish',
  'crab',
  'rooster',
] as const

export const SYMBOLS_MAP: Record<SymbolId, SymbolInfo> = {
  tiger: {
    id: 'tiger',
    englishName: 'Tiger',
    khmerName: 'ខ្លា',
    ipa: '/kʰlaː/',
    meaning: 'Bravery, strength, royal dominion, and fierce power',
    description: 'Lord of the forest (Bravery & Power)',
    gridOrder: 0,
    colorPalette: {
      primary: '#EA580C',
      secondary: '#F97316',
      accent: '#FEF08A',
      bgClass: 'bg-gradient-to-br from-amber-900/60 to-orange-950/80',
      borderClass: 'border-amber-500/60 focus:border-amber-400 hover:border-amber-400',
      textClass: 'text-amber-400',
      glowClass: 'shadow-amber-500/30',
    },
  },
  gourd: {
    id: 'gourd',
    englishName: 'Gourd',
    khmerName: 'ឃ្លោក',
    ipa: '/kʰloːk/',
    meaning: 'Longevity, health, bottle of abundance, container of good fortune',
    description: 'Calabash gourd (Health & Abundance)',
    gridOrder: 1,
    colorPalette: {
      primary: '#16A34A',
      secondary: '#22C55E',
      accent: '#BBF7D0',
      bgClass: 'bg-gradient-to-br from-emerald-900/60 to-green-950/80',
      borderClass: 'border-emerald-500/60 focus:border-emerald-400 hover:border-emerald-400',
      textClass: 'text-emerald-400',
      glowClass: 'shadow-emerald-500/30',
    },
  },
  shrimp: {
    id: 'shrimp',
    englishName: 'Shrimp',
    khmerName: 'បង្កង',
    ipa: '/ɓɑŋ.kɑːŋ/',
    meaning: 'Prosperity, agility, aquatic harvest, and renewal',
    description: 'River prawn (Agility & Prosperity)',
    gridOrder: 2,
    colorPalette: {
      primary: '#EF4444',
      secondary: '#F87171',
      accent: '#FECDD3',
      bgClass: 'bg-gradient-to-br from-rose-900/60 to-red-950/80',
      borderClass: 'border-rose-500/60 focus:border-rose-400 hover:border-rose-400',
      textClass: 'text-rose-400',
      glowClass: 'shadow-rose-500/30',
    },
  },
  fish: {
    id: 'fish',
    englishName: 'Fish',
    khmerName: 'ត្រី',
    ipa: '/trəj/',
    meaning: 'Abundance, wealth, prosperity, peaceful life, and fluidity',
    description: 'Freshwater fish (Wealth & Abundance)',
    gridOrder: 3,
    colorPalette: {
      primary: '#2563EB',
      secondary: '#38BDF8',
      accent: '#BAE6FD',
      bgClass: 'bg-gradient-to-br from-sky-900/60 to-blue-950/80',
      borderClass: 'border-sky-500/60 focus:border-sky-400 hover:border-sky-400',
      textClass: 'text-sky-400',
      glowClass: 'shadow-sky-500/30',
    },
  },
  crab: {
    id: 'crab',
    englishName: 'Crab',
    khmerName: 'ក្តាម',
    ipa: '/kdaːm/',
    meaning: 'Resourcefulness, persistence, tenacity, and good harvest',
    description: 'Mud crab (Tenacity & Good harvest)',
    gridOrder: 4,
    colorPalette: {
      primary: '#DC2626',
      secondary: '#B91C1C',
      accent: '#FED7AA',
      bgClass: 'bg-gradient-to-br from-red-900/60 to-stone-950/80',
      borderClass: 'border-red-600/60 focus:border-red-500 hover:border-red-500',
      textClass: 'text-red-400',
      glowClass: 'shadow-red-500/30',
    },
  },
  rooster: {
    id: 'rooster',
    englishName: 'Rooster',
    khmerName: 'មាន់',
    ipa: '/mŏən/',
    meaning: 'Punctuality, awakening, prosperity, vigilance, and good luck at dawn',
    description: 'Morning rooster (Vigilance & Fortune)',
    gridOrder: 5,
    colorPalette: {
      primary: '#EAB308',
      secondary: '#F59E0B',
      accent: '#FEF9C3',
      bgClass: 'bg-gradient-to-br from-yellow-900/60 to-amber-950/80',
      borderClass: 'border-yellow-500/60 focus:border-yellow-400 hover:border-yellow-400',
      textClass: 'text-yellow-400',
      glowClass: 'shadow-yellow-500/30',
    },
  },
}

export const SYMBOLS_LIST: SymbolInfo[] = Object.values(SYMBOLS_MAP).sort(
  (a, b) => a.gridOrder - b.gridOrder,
)

export const EMPTY_BET_MAP: BetMap = {
  tiger: 0,
  gourd: 0,
  shrimp: 0,
  fish: 0,
  crab: 0,
  rooster: 0,
}
