import type { CoreClient } from '../core/core-client.js'
import { isFastActionDeterministicRead, normalizedActionKind, type FastAction, type FastActionPlan } from '../../shared/fast-action.js'
export const ND_FAST_PATH_ENGINE_ID='nd-fast-path'
export interface FastPathAuditRecord{companyId:string;projectId:string;taskId:string;action:string;target:string;scope:string;risk:'low'|'medium'|'high'|'critical';externality:'internal'|'external';destructiveLevel:'none'|'reversible'|'destructive';credentialScope:string[];engine:string;agentId?:string;capability?:string;provenance:string[];requestedAt:number;decision:'allow'|'ask'|'deny';reason:string}
export type FastPathAuditRecorder=(r:FastPathAuditRecord)=>Promise<void>
export interface PreparedFastPath{root:string;plan:FastActionPlan;actions:FastAction[]}
export class FastPathPolicyError extends Error{readonly code='fast-path-policy'}
export async function prepareFastPath(input:{plan:FastActionPlan;context:{company:{id:string};project:{id:string};task:{id:string};agent?:{id:string}};root:string;explicit:boolean;policy:(a:string)=>Promise<'allow'|'ask'|'deny'>;audit:FastPathAuditRecorder}){for(const action of input.plan.actions){const e=envelope(action,input.context,input.root),decision=await input.policy(e.action);await input.audit({...e,companyId:input.context.company.id,projectId:input.context.project.id,taskId:input.context.task.id,decision,reason:'Typed fast-action policy evaluated before execution.'});if(decision==='deny')throw new FastPathPolicyError('Company policy denied '+e.action);if(decision==='ask'&&!input.explicit)throw new FastPathPolicyError('Fast action requires human approval: '+e.action)}const unsupported=input.plan.actions.find(a=>!isFastActionDeterministicRead(a));if(unsupported||!input.plan.actions.some(a=>a.verb==='DONE')){const reason=unsupported?'Fast action '+unsupported.verb+' requires the normal reasoning/action path.':'Fast-action plan has no DONE action.';const decision=await input.policy('runtime.escalation');await input.audit({companyId:input.context.company.id,projectId:input.context.project.id,taskId:input.context.task.id,action:'runtime.escalation',target:reason,scope:input.root,risk:'medium',externality:'internal',destructiveLevel:'none',credentialScope:[],engine:ND_FAST_PATH_ENGINE_ID,...(input.context.agent?.id?{agentId:input.context.agent.id}:{}),capability:'model-runtime',provenance:['organization-task:'+input.context.task.id],requestedAt:Date.now(),decision,reason});if(decision==='deny'||(decision==='ask'&&!input.explicit))throw new FastPathPolicyError('Runtime escalation is not allowed.');return{kind:'escalate' as const,reason}}return{kind:'ready' as const,prepared:{root:input.root,plan:input.plan,actions:input.plan.actions}}}
export async function executePreparedFastPath(p:PreparedFastPath,core:Pick<CoreClient,'request'>){const reads=p.actions.filter(a=>a.verb==='READ_FILE').map(a=>{const x=a as Extract<FastAction,{verb:'READ_FILE'}>;return{path:x.params.path,...(x.params.maxBytes===undefined?{}:{maxBytes:x.params.maxBytes})}}),searches=p.actions.filter(a=>a.verb==='SEARCH_CODE').map(a=>({...((a as Extract<FastAction,{verb:'SEARCH_CODE'}>).params)})),includeGitStatus=p.actions.some(a=>a.verb==='CHECK_GIT'&&a.params.operation==='status');const s=await core.request<any>('workspace.snapshot',{root:p.root,reads,searches,includeGitStatus,...(p.plan.expectedRevision?{expectedRevision:p.plan.expectedRevision}:{})},20000);if(s.stale)throw new Error('Fast-path workspace revision is stale: '+s.revision.value);if(s.truncated)throw new Error('Fast-path composite snapshot was truncated.');let r=0,q=0;const actions=p.actions.map(a=>a.verb==='READ_FILE'?{verb:a.verb,result:s.reads[r++]}:a.verb==='SEARCH_CODE'?{verb:a.verb,result:s.searches[q++]}:a.verb==='CHECK_GIT'?{verb:a.verb,result:{operation:'status',...(s.gitStatus??{})}}:a.verb==='OPEN_FILE'?{verb:a.verb,result:{...a.params,opened:false}}:a.verb==='DONE'?{verb:a.verb,result:{completed:true,summary:a.params.summary}}:(()=>{throw new Error('Non-deterministic action reached executor.')})());return{revision:s.revision.value,output:'<nd-dsh-fast-path>'+JSON.stringify({engine:ND_FAST_PATH_ENGINE_ID,revision:s.revision.value,actions})+'</nd-dsh-fast-path>'}}
function envelope(a:FastAction,c:{agent?:{id:string}},root:string){const kind=normalizedActionKind(a),m=['source.write','shell.execute','git.commit','git.push'].includes(kind),x=kind==='git.push';return{action:kind,target:a.verb==='READ_FILE'||a.verb==='OPEN_FILE'?a.params.path:a.verb==='SEARCH_CODE'?a.params.path??'.':a.verb==='CHECK_GIT'?'git:'+a.params.operation:a.verb==='RUN_COMMAND'?a.params.command.slice(0,512):a.verb.toLowerCase(),scope:a.writeScope.length?a.writeScope.join(','):root,risk:(x?'high':m?'medium':'low') as 'low'|'medium'|'high',externality:(x?'external':'internal') as 'external'|'internal',destructiveLevel:(m?'reversible':'none') as 'reversible'|'none',credentialScope:x?['git-remote']:[],engine:ND_FAST_PATH_ENGINE_ID,...(c.agent?.id?{agentId:c.agent.id}:{}),capability:kind.startsWith('git.')?'git':kind.startsWith('source.')?'workspace':'organization',provenance:['fast-action:'+a.verb],requestedAt:Date.now()}}
